-- Create project_items table
CREATE TABLE IF NOT EXISTS project_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
  item_name TEXT NOT NULL,
  area TEXT,
  description TEXT,
  supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
  category categoria_item NOT NULL DEFAULT 'Otro',
  quantity INTEGER DEFAULT 1,
  estimated_cost DECIMAL(12, 2),
  internal_cost DECIMAL(12, 2),
  client_cost DECIMAL(12, 2),
  status TEXT, -- Using text field instead of enum for flexibility
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create trigger for updated_at
CREATE TRIGGER update_project_items_updated_at
BEFORE UPDATE ON project_items
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();