-- Create projects table
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  client_id BIGINT REFERENCES clients(id) ON DELETE CASCADE,
  start_date DATE,
  estimated_completion DATE,
  budget DECIMAL(12, 2),
  status estado_proyecto NOT NULL DEFAULT 'Planificación',
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create trigger for updated_at
CREATE TRIGGER update_projects_updated_at
BEFORE UPDATE ON projects
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();